name: CI/CD Pipeline
on:
  push:
    branches: 
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          -name: run install, build and test
            run: | 
              npm install
              npm run build
              npm run testd
